# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Notes on GitHub Actions
# The default shell on Windows is pwsh.exe (see: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell)

name: Build Basic Console App (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      DEBUG_WORKFLOW:
        description: 'Flag to display more information if debugging workflow'
        required: false
        type: boolean
        default: false
      VERSION_MAJOR:
        description: 'Version (major)'
        required: false
        type: number
        default: 1
      VERSION_MINOR:
        description: 'Version (minor)'
        required: false
        type: number
        default: 0
      VERSION_BUILD:
        description: 'Version (build)'
        required: false
        type: number
        default: 0
      BUILD_CONFIGURATION:
        description: "Build configuration"
        required: false
        type: string
        default: "Release"

jobs:
  "build":
    runs-on: [self-hosted, Windows, minikube]
    
    defaults:
      run:
        shell: cmd
        working-directory: ${{ github.workspace }}

    steps:
    - name: Print GITHUB_EVENT_NAME
      run: echo "GITHUB_EVENT_NAME is ${{ github.event_name }} or ${{ env.GITHUB_EVENT_NAME }} END"
    - name: Print GITHUB_EVENT_NAME
      run: echo "OKOK"
      if: github.GITHUB_EVENT_NAME == 'workflow_dispatch'
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: "Add version info to json file"
      env:
        BUILD_VERSION: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
      run: |
        echo "version: ${{ env.BUILD_VERSION }}"

    - name: Print inputs
      run: echo "debug_workflow is ${{ inputs.DEBUG_WORKFLOW }} or ${{ inputs.debug_workflow }} END"
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Dump selected variables
      run: |
        echo "GitHub SHA: $GITHUB_SHA"
        echo "GitHub Workspace1: ${GITHUB_WORKSPACE}"
        echo "GitHub Workspace2: $GITHUB_WORKSPACE"
        echo "GitHub Workspace3: $env:GITHUB_WORKSPACE"
        echo "GitHub Workspace4: $($env:GITHUB_WORKSPACE)"
        echo "GitHub Workspace5: ${{ github.workspace }}"
        echo "GitHub Workspace6: ${{ inputs.working_directory }}"
        whoami
        
    - name: Dump environment variables
      run: set
    - name: List files
      run: dir
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
