# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Notes on GitHub Actions
# The default shell on Windows is pwsh.exe (see: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell)

name: Build Console App (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_workflow:
        description: 'Print out more information for debugging'
        type: boolean
        required: true
        default: false

jobs:
  "build":
    runs-on: [self-hosted, Windows, minikube]
    defaults:
      run:
        shell: cmd
        working-directory: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Dump environment variables
      run: set
    - name: Print inputs
      run: echo "debug_workflow is ${{ inputs.debug_workflow }}"
    - name: Dump selected variables
      run: |
        echo "GitHub SHA: $GITHUB_SHA"
        echo "GitHub Workspace1: ${GITHUB_WORKSPACE}"
        echo "GitHub Workspace2: $GITHUB_WORKSPACE"
        echo "GitHub Workspace3: $env:GITHUB_WORKSPACE"
        echo "GitHub Workspace4: $($env:GITHUB_WORKSPACE)"
        echo "GitHub Workspace5: ${{ github.workspace }}"
        echo "GitHub Workspace6: ${{ inputs.working_directory }}"
        whoami
        
    - name: List files
      run: dir /s
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
