# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Notes on GitHub Actions
# The default shell on Windows is pwsh.exe (see: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell)

name: Build Basic Console App (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      DEBUG_WORKFLOW:
        description: 'Flag to display more information if debugging workflow'
        required: false
        type: boolean
        default: false
      VERSION_MAJOR:
        description: 'Version (major)'
        required: false
        type: number
        default: 1
      VERSION_MINOR:
        description: 'Version (minor)'
        required: false
        type: number
        default: 0
      VERSION_BUILD:
        description: 'Version (build)'
        required: false
        type: number
        default: 0
      BUILD_CONFIGURATION:
        description: "Build configuration"
        required: false
        type: string
        default: "Release"
        
env:
  MY_BUILD_VERSION: "${{ inputs.VERSION_MAJOR || vars.BUILD_VERSION_MAJOR }}.${{ inputs.VERSION_MINOR || vars.BUILD_VERSION_MINOR }}.${{ inputs.VERSION_BUILD || github.run_number }}.${{ github.run_attempt }}"
  BUILD_CONFIGURATION: "${{ inputs.BUILD_CONFIGURATION || 'Release' }}"
  DEBUG_WORKFLOW: "${{ inputs.DEBUG_WORKFLOW || false }}"
  ARTIFACT_NAME: "ConsoleApp"
  
jobs:
  Build:
    runs-on: [self-hosted, Windows, minikube, powerShellCore]

    defaults:
      run:
        shell: cmd
        working-directory: ${{ github.workspace }}

    steps:
    - name: Print job environment variables
      run: |
        echo MY_BUILD_VERSION     : ${{ env.MY_BUILD_VERSION }}
        echo BUILD_CONFIGURATION  : ${{ env.BUILD_CONFIGURATION }}
        echo DEBUG_WORKFLOW       : ${{ env.DEBUG_WORKFLOW }}
        echo ARTIFACT_NAME        : ${{ env.ARTIFACT_NAME }}
        
    - name: Print debug information (DEBUG_WORKFLOW is ${{ env.DEBUG_WORKFLOW }}) 
      if: env.DEBUG_WORKFLOW == true
      run: |
        echo GITHUB_EVENT_NAME      : ${{ github.event_name }}
        set
        dir
      
    - name: Print configuration variables (DEBUG_WORKFLOW is ${{ env.DEBUG_WORKFLOW }})
      if: env.DEBUG_WORKFLOW == true
      run: |
        echo SAMPLE_ORG_VARIABLE1   : ${{ vars.SAMPLE_ORG_VARIABLE1 }}
        echo SAMPLE_REPO_VARIABLE1  : ${{ vars.SAMPLE_REPO_VARIABLE1 }}
        echo SAMPLE_REPO_SECRET1    : ${{ secrets.SAMPLE_REPO_SECRET1 }}
        echo SAMPLE_ORG_SECRET1     : ${{ secrets.SAMPLE_ORG_SECRET1 }}
        echo SAMPLE_ORG_SECRET2     : ${{ secrets.SAMPLE_ORG_SECRET2 }}

    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x      
    - name: Restore dependencies
      run: dotnet restore --artifacts-path ./artifacts
    - name: Build
      run: dotnet build --nologo --no-restore --configuration ${{ env.BUILD_CONFIGURATION }} -p:AssemblyVersion=${{ env.MY_BUILD_VERSION }} --artifacts-path ./artifacts
    - name: Test
      run: dotnet test --nologo --no-restore --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --artifacts-path ./artifacts 
    - name: Publish
      run: dotnet publish --nologo --no-restore --no-build --configuration ${{ env.BUILD_CONFIGURATION }} --artifacts-path ./artifacts
    - name: Archive
      env:
        ARTIFACT_ARCHIVE_NAME: "${{ env.ARTIFACT_NAME }}-${{ env.BUILD_CONFIGURATION }}-${{ env.MY_BUILD_VERSION }}.zip"
      run: |
        dir
        pwsh.exe -NoLogo -NoProfile -WorkingDirectory ${{ github.workspace }} -Command Compress-Archive "./artifacts/publish/BasicConsoleApp/${{ env.BUILD_CONFIGURATION }}" "./${{ env.ARTIFACT_ARCHIVE_NAME }}" -Force
        echo ARTIFACT_ARCHIVE_NAME: [${{ env.ARTIFACT_ARCHIVE_NAME }}]
    - name: Upload dotnet test results
      env:
        ARTIFACT_ARCHIVE_NAME: "${{ env.ARTIFACT_NAME }}-${{ env.BUILD_CONFIGURATION }}-${{ env.MY_BUILD_VERSION }}.zip"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_ARCHIVE_NAME }}
        path: "./${{ env.ARTIFACT_ARCHIVE_NAME }}"    
    - name: Post-job
      run: |
        set
        dir


