# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Notes on GitHub Actions
# The default shell on Windows is pwsh.exe (see: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell)

name: Build Basic Console App (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      DEBUG_WORKFLOW:
        description: 'Flag to display more information if debugging workflow'
        required: false
        type: boolean
        default: false
      VERSION_MAJOR:
        description: 'Version (major)'
        required: false
        type: number
        default: 1
      VERSION_MINOR:
        description: 'Version (minor)'
        required: false
        type: number
        default: 0
      VERSION_BUILD:
        description: 'Version (build)'
        required: false
        type: number
        default: 0
      BUILD_CONFIGURATION:
        description: "Build configuration"
        required: false
        type: string
        default: "Release"
        
env:
  MY_BUILD_VERSION: "${{ inputs.VERSION_MAJOR || vars.BUILD_VERSION_MAJOR }}.${{ inputs.VERSION_MINOR || vars.BUILD_VERSION_MINOR }}.${{ inputs.VERSION_BUILD || github.run_number }}.${{ github.run_attempt }}"
  BUILD_CONFIGURATION: "${{ inputs.BUILD_CONFIGURATION || 'Release' }}"
  DEBUG_WORKFLOW: "${{ inputs.DEBUG_WORKFLOW || false }}"
  
jobs:
  "build":
    runs-on: [self-hosted, Windows, minikube]
    
    defaults:
      run:
        shell: cmd
        working-directory: ${{ github.workspace }}


    steps:
    - name: Print GITHUB_EVENT_NAME
      run: echo "GITHUB_EVENT_NAME is ${{ github.event_name }} or ${{ env.GITHUB_EVENT_NAME }} END -- ${{ env.MY_BUILD_VERSION }}"
      
    - name: Print inputs is null
      run: echo "Yeah inputs is null"
      if: inputs == null
      
    - name: Print if DEBUG_WORKFLOW 
      run: echo "Yeah DEBUG_WORKFLOW is true"
      if: ${{ env.DEBUG_WORKFLOW == true }}
      
    - name: Print if NOT DEBUG_WORKFLOW
      run: echo "Yeah DEBUG_WORKFLOW is FALSE"
      if: ${{ !env.DEBUG_WORKFLOW == false }}
      
    - name: Print if DEBUG_WORKFLOW
      run: echo "Yeah DEBUG_WORKFLOW is true 2"
      if: env.DEBUG_WORKFLOW == true
      
    - name: Print inputs is NOT null (before)
      run: |
        echo "Yeah inputs is NOT null"
        echo "DEBUG_WORKFLOW      : ${{ inputs.DEBUG_WORKFLOW }}"
        echo "VERSION_MAJOR       : ${{ inputs.VERSION_MAJOR }}"
        echo "VERSION_MINOR       : ${{ inputs.VERSION_MINOR }}"
        echo "VERSION_BUILD       : ${{ inputs.VERSION_BUILD }}"
        echo "BUILD_CONFIGURATION : ${{ inputs.BUILD_CONFIGURATION }}"
      if: inputs != null

    - name: Print config vars
      run: |
        echo "SAMPLE_ORG_VARIABLE1  : ${{ vars.SAMPLE_ORG_VARIABLE1 }}"
        echo "SAMPLE_REPO_VARIABLE1 : ${{ vars.SAMPLE_REPO_VARIABLE1 }}"
        echo "SAMPLE_REPO_SECRET1   : ${{ vars.SAMPLE_REPO_SECRET1 }}"
        echo "SAMPLE_ORG_SECRET1    : ${{ vars.SAMPLE_ORG_SECRET1 }}"
        echo "SAMPLE_ORG_SECRET2    : ${{ vars.SAMPLE_ORG_SECRET2 }}"
      
    - name: Print GITHUB_EVENT_NAME
      run: echo "OKOK"
      if: github.event_name == 'workflow_dispatch'
    - name: Print GITHUB_EVENT_NAME
      run: echo "OKOK IS PULL REQUEST"
      if: github.event_name == 'pull_request'
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - name: "Add version info to json file"
      env:
        BUILD_VERSION: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
      run: |
        echo "version: ${{ env.BUILD_VERSION }}"

    - name: Print inputs
      run: echo "debug_workflow is ${{ inputs.DEBUG_WORKFLOW }} or ${{ inputs.debug_workflow }} END"
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Dump selected variables
      run: |
        echo "GitHub SHA: $GITHUB_SHA"
        echo "GitHub Workspace1: ${GITHUB_WORKSPACE}"
        echo "GitHub Workspace2: $GITHUB_WORKSPACE"
        echo "GitHub Workspace3: $env:GITHUB_WORKSPACE"
        echo "GitHub Workspace4: $($env:GITHUB_WORKSPACE)"
        echo "GitHub Workspace5: ${{ github.workspace }}"
        echo "GitHub Workspace6: ${{ inputs.working_directory }}"
        whoami
        
    - name: Dump environment variables
      run: set
    - name: List files
      run: dir
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
